apiVersion: v1
kind: Pod
metadata:
  name: centaurx
spec:
  containers:
    - name: centaurx
      image: docker.io/pktsystems/centaurx:v0.1.1-0.20260106185608-de4efe56c476
      args: ["serve", "-c", "/cx/config-for-container.yaml"]
      env:
        - name: HOME
          value: /centaurx
      ports:
        - containerPort: 27480
          hostPort: 27480
          protocol: TCP
        - containerPort: 27422
          hostPort: 27422
          protocol: TCP
      securityContext:
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: centaurx-state
          mountPath: /cx/state
        - name: centaurx-repos
          mountPath: /cx/repos
        - name: centaurx-config
          mountPath: /cx/config-for-container.yaml
          readOnly: true
        - name: podman-sock
          mountPath: /cx/podman.sock
          readOnly: true
        - name: tmp
          mountPath: /tmp
        - name: run
          mountPath: /run
        - name: var-run
          mountPath: /var/run
        - name: var-tmp
          mountPath: /var/tmp
        - name: centaurx-home
          mountPath: /centaurx
  volumes:
    - name: centaurx-state
      hostPath:
        path: ${HOME}/.centaurx/state
        type: DirectoryOrCreate
    - name: centaurx-repos
      hostPath:
        path: ${HOME}/.centaurx/repos
        type: DirectoryOrCreate
    - name: centaurx-config
      hostPath:
        path: ${HOME}/.centaurx/config-for-container.yaml
        type: File
    - name: podman-sock
      hostPath:
        path: /run/user/${UID}/podman/podman.sock
        type: Socket
    - name: tmp
      emptyDir:
        medium: Memory
    - name: run
      emptyDir:
        medium: Memory
    - name: var-run
      emptyDir:
        medium: Memory
    - name: var-tmp
      emptyDir:
        medium: Memory
    - name: centaurx-home
      emptyDir:
        medium: Memory
