// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/runner/v1/runner.proto

package runnerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runner_Exec_FullMethodName          = "/centaurx.runner.v1.Runner/Exec"
	Runner_ExecResume_FullMethodName    = "/centaurx.runner.v1.Runner/ExecResume"
	Runner_RunCommand_FullMethodName    = "/centaurx.runner.v1.Runner/RunCommand"
	Runner_Ping_FullMethodName          = "/centaurx.runner.v1.Runner/Ping"
	Runner_SignalSession_FullMethodName = "/centaurx.runner.v1.Runner/SignalSession"
	Runner_GetUsage_FullMethodName      = "/centaurx.runner.v1.Runner/GetUsage"
)

// RunnerClient is the client API for Runner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerClient interface {
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunnerEvent], error)
	ExecResume(ctx context.Context, in *ExecResumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunnerEvent], error)
	RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunnerEvent], error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	SignalSession(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	GetUsage(ctx context.Context, in *UsageRequest, opts ...grpc.CallOption) (*UsageResponse, error)
}

type runnerClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerClient(cc grpc.ClientConnInterface) RunnerClient {
	return &runnerClient{cc}
}

func (c *runnerClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunnerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runner_ServiceDesc.Streams[0], Runner_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, RunnerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_ExecClient = grpc.ServerStreamingClient[RunnerEvent]

func (c *runnerClient) ExecResume(ctx context.Context, in *ExecResumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunnerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runner_ServiceDesc.Streams[1], Runner_ExecResume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecResumeRequest, RunnerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_ExecResumeClient = grpc.ServerStreamingClient[RunnerEvent]

func (c *runnerClient) RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunnerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runner_ServiceDesc.Streams[2], Runner_RunCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunCommandRequest, RunnerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_RunCommandClient = grpc.ServerStreamingClient[RunnerEvent]

func (c *runnerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Runner_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) SignalSession(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, Runner_SignalSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) GetUsage(ctx context.Context, in *UsageRequest, opts ...grpc.CallOption) (*UsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageResponse)
	err := c.cc.Invoke(ctx, Runner_GetUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerServer is the server API for Runner service.
// All implementations must embed UnimplementedRunnerServer
// for forward compatibility.
type RunnerServer interface {
	Exec(*ExecRequest, grpc.ServerStreamingServer[RunnerEvent]) error
	ExecResume(*ExecResumeRequest, grpc.ServerStreamingServer[RunnerEvent]) error
	RunCommand(*RunCommandRequest, grpc.ServerStreamingServer[RunnerEvent]) error
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	SignalSession(context.Context, *SignalRequest) (*SignalResponse, error)
	GetUsage(context.Context, *UsageRequest) (*UsageResponse, error)
	mustEmbedUnimplementedRunnerServer()
}

// UnimplementedRunnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerServer struct{}

func (UnimplementedRunnerServer) Exec(*ExecRequest, grpc.ServerStreamingServer[RunnerEvent]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedRunnerServer) ExecResume(*ExecResumeRequest, grpc.ServerStreamingServer[RunnerEvent]) error {
	return status.Error(codes.Unimplemented, "method ExecResume not implemented")
}
func (UnimplementedRunnerServer) RunCommand(*RunCommandRequest, grpc.ServerStreamingServer[RunnerEvent]) error {
	return status.Error(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedRunnerServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRunnerServer) SignalSession(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalSession not implemented")
}
func (UnimplementedRunnerServer) GetUsage(context.Context, *UsageRequest) (*UsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsage not implemented")
}
func (UnimplementedRunnerServer) mustEmbedUnimplementedRunnerServer() {}
func (UnimplementedRunnerServer) testEmbeddedByValue()                {}

// UnsafeRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServer will
// result in compilation errors.
type UnsafeRunnerServer interface {
	mustEmbedUnimplementedRunnerServer()
}

func RegisterRunnerServer(s grpc.ServiceRegistrar, srv RunnerServer) {
	// If the following call panics, it indicates UnimplementedRunnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runner_ServiceDesc, srv)
}

func _Runner_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServer).Exec(m, &grpc.GenericServerStream[ExecRequest, RunnerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_ExecServer = grpc.ServerStreamingServer[RunnerEvent]

func _Runner_ExecResume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecResumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServer).ExecResume(m, &grpc.GenericServerStream[ExecResumeRequest, RunnerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_ExecResumeServer = grpc.ServerStreamingServer[RunnerEvent]

func _Runner_RunCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServer).RunCommand(m, &grpc.GenericServerStream[RunCommandRequest, RunnerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_RunCommandServer = grpc.ServerStreamingServer[RunnerEvent]

func _Runner_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_SignalSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).SignalSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_SignalSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).SignalSession(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_GetUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).GetUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_GetUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).GetUsage(ctx, req.(*UsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Runner_ServiceDesc is the grpc.ServiceDesc for Runner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "centaurx.runner.v1.Runner",
	HandlerType: (*RunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Runner_Ping_Handler,
		},
		{
			MethodName: "SignalSession",
			Handler:    _Runner_SignalSession_Handler,
		},
		{
			MethodName: "GetUsage",
			Handler:    _Runner_GetUsage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _Runner_Exec_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecResume",
			Handler:       _Runner_ExecResume_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunCommand",
			Handler:       _Runner_RunCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/runner/v1/runner.proto",
}
