// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/runner/v1/runner.proto

package runnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessSignal int32

const (
	ProcessSignal_PROCESS_SIGNAL_UNSPECIFIED ProcessSignal = 0
	ProcessSignal_PROCESS_SIGNAL_HUP         ProcessSignal = 1
	ProcessSignal_PROCESS_SIGNAL_TERM        ProcessSignal = 2
	ProcessSignal_PROCESS_SIGNAL_KILL        ProcessSignal = 3
)

// Enum value maps for ProcessSignal.
var (
	ProcessSignal_name = map[int32]string{
		0: "PROCESS_SIGNAL_UNSPECIFIED",
		1: "PROCESS_SIGNAL_HUP",
		2: "PROCESS_SIGNAL_TERM",
		3: "PROCESS_SIGNAL_KILL",
	}
	ProcessSignal_value = map[string]int32{
		"PROCESS_SIGNAL_UNSPECIFIED": 0,
		"PROCESS_SIGNAL_HUP":         1,
		"PROCESS_SIGNAL_TERM":        2,
		"PROCESS_SIGNAL_KILL":        3,
	}
)

func (x ProcessSignal) Enum() *ProcessSignal {
	p := new(ProcessSignal)
	*p = x
	return p
}

func (x ProcessSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runner_v1_runner_proto_enumTypes[0].Descriptor()
}

func (ProcessSignal) Type() protoreflect.EnumType {
	return &file_proto_runner_v1_runner_proto_enumTypes[0]
}

func (x ProcessSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessSignal.Descriptor instead.
func (ProcessSignal) EnumDescriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{0}
}

type RunState int32

const (
	RunState_RUN_STATE_UNSPECIFIED RunState = 0
	RunState_RUN_STATE_STARTED     RunState = 1
	RunState_RUN_STATE_FINISHED    RunState = 2
	RunState_RUN_STATE_FAILED      RunState = 3
)

// Enum value maps for RunState.
var (
	RunState_name = map[int32]string{
		0: "RUN_STATE_UNSPECIFIED",
		1: "RUN_STATE_STARTED",
		2: "RUN_STATE_FINISHED",
		3: "RUN_STATE_FAILED",
	}
	RunState_value = map[string]int32{
		"RUN_STATE_UNSPECIFIED": 0,
		"RUN_STATE_STARTED":     1,
		"RUN_STATE_FINISHED":    2,
		"RUN_STATE_FAILED":      3,
	}
)

func (x RunState) Enum() *RunState {
	p := new(RunState)
	*p = x
	return p
}

func (x RunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runner_v1_runner_proto_enumTypes[1].Descriptor()
}

func (RunState) Type() protoreflect.EnumType {
	return &file_proto_runner_v1_runner_proto_enumTypes[1]
}

func (x RunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunState.Descriptor instead.
func (RunState) EnumDescriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{1}
}

type StreamKind int32

const (
	StreamKind_STREAM_KIND_UNSPECIFIED StreamKind = 0
	StreamKind_STREAM_KIND_STDOUT      StreamKind = 1
	StreamKind_STREAM_KIND_STDERR      StreamKind = 2
)

// Enum value maps for StreamKind.
var (
	StreamKind_name = map[int32]string{
		0: "STREAM_KIND_UNSPECIFIED",
		1: "STREAM_KIND_STDOUT",
		2: "STREAM_KIND_STDERR",
	}
	StreamKind_value = map[string]int32{
		"STREAM_KIND_UNSPECIFIED": 0,
		"STREAM_KIND_STDOUT":      1,
		"STREAM_KIND_STDERR":      2,
	}
)

func (x StreamKind) Enum() *StreamKind {
	p := new(StreamKind)
	*p = x
	return p
}

func (x StreamKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runner_v1_runner_proto_enumTypes[2].Descriptor()
}

func (StreamKind) Type() protoreflect.EnumType {
	return &file_proto_runner_v1_runner_proto_enumTypes[2]
}

func (x StreamKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamKind.Descriptor instead.
func (StreamKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{2}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_THREAD_STARTED   EventType = 1
	EventType_EVENT_TURN_STARTED     EventType = 2
	EventType_EVENT_TURN_COMPLETED   EventType = 3
	EventType_EVENT_TURN_FAILED      EventType = 4
	EventType_EVENT_ITEM_STARTED     EventType = 5
	EventType_EVENT_ITEM_UPDATED     EventType = 6
	EventType_EVENT_ITEM_COMPLETED   EventType = 7
	EventType_EVENT_ERROR            EventType = 8
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_THREAD_STARTED",
		2: "EVENT_TURN_STARTED",
		3: "EVENT_TURN_COMPLETED",
		4: "EVENT_TURN_FAILED",
		5: "EVENT_ITEM_STARTED",
		6: "EVENT_ITEM_UPDATED",
		7: "EVENT_ITEM_COMPLETED",
		8: "EVENT_ERROR",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_THREAD_STARTED":   1,
		"EVENT_TURN_STARTED":     2,
		"EVENT_TURN_COMPLETED":   3,
		"EVENT_TURN_FAILED":      4,
		"EVENT_ITEM_STARTED":     5,
		"EVENT_ITEM_UPDATED":     6,
		"EVENT_ITEM_COMPLETED":   7,
		"EVENT_ERROR":            8,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runner_v1_runner_proto_enumTypes[3].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_runner_v1_runner_proto_enumTypes[3]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{3}
}

type ItemType int32

const (
	ItemType_ITEM_TYPE_UNSPECIFIED  ItemType = 0
	ItemType_ITEM_AGENT_MESSAGE     ItemType = 1
	ItemType_ITEM_REASONING         ItemType = 2
	ItemType_ITEM_COMMAND_EXECUTION ItemType = 3
	ItemType_ITEM_FILE_CHANGE       ItemType = 4
	ItemType_ITEM_MCP_TOOL_CALL     ItemType = 5
	ItemType_ITEM_WEB_SEARCH        ItemType = 6
	ItemType_ITEM_TODO_LIST         ItemType = 7
	ItemType_ITEM_ERROR             ItemType = 8
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ITEM_TYPE_UNSPECIFIED",
		1: "ITEM_AGENT_MESSAGE",
		2: "ITEM_REASONING",
		3: "ITEM_COMMAND_EXECUTION",
		4: "ITEM_FILE_CHANGE",
		5: "ITEM_MCP_TOOL_CALL",
		6: "ITEM_WEB_SEARCH",
		7: "ITEM_TODO_LIST",
		8: "ITEM_ERROR",
	}
	ItemType_value = map[string]int32{
		"ITEM_TYPE_UNSPECIFIED":  0,
		"ITEM_AGENT_MESSAGE":     1,
		"ITEM_REASONING":         2,
		"ITEM_COMMAND_EXECUTION": 3,
		"ITEM_FILE_CHANGE":       4,
		"ITEM_MCP_TOOL_CALL":     5,
		"ITEM_WEB_SEARCH":        6,
		"ITEM_TODO_LIST":         7,
		"ITEM_ERROR":             8,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runner_v1_runner_proto_enumTypes[4].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_proto_runner_v1_runner_proto_enumTypes[4]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{4}
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Json          bool                   `protobuf:"varint,5,opt,name=json,proto3" json:"json,omitempty"`
	SshAuthSock   string                 `protobuf:"bytes,6,opt,name=ssh_auth_sock,json=sshAuthSock,proto3" json:"ssh_auth_sock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExecRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *ExecRequest) GetSshAuthSock() string {
	if x != nil {
		return x.SshAuthSock
	}
	return ""
}

type ExecResumeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkingDir      string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Prompt          string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model           string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	ResumeSessionId string                 `protobuf:"bytes,5,opt,name=resume_session_id,json=resumeSessionId,proto3" json:"resume_session_id,omitempty"`
	Json            bool                   `protobuf:"varint,6,opt,name=json,proto3" json:"json,omitempty"`
	SshAuthSock     string                 `protobuf:"bytes,7,opt,name=ssh_auth_sock,json=sshAuthSock,proto3" json:"ssh_auth_sock,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecResumeRequest) Reset() {
	*x = ExecResumeRequest{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResumeRequest) ProtoMessage() {}

func (x *ExecResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResumeRequest.ProtoReflect.Descriptor instead.
func (*ExecResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResumeRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecResumeRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecResumeRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecResumeRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExecResumeRequest) GetResumeSessionId() string {
	if x != nil {
		return x.ResumeSessionId
	}
	return ""
}

func (x *ExecResumeRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *ExecResumeRequest) GetSshAuthSock() string {
	if x != nil {
		return x.SshAuthSock
	}
	return ""
}

type RunCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	UseShell      bool                   `protobuf:"varint,4,opt,name=use_shell,json=useShell,proto3" json:"use_shell,omitempty"`
	SshAuthSock   string                 `protobuf:"bytes,5,opt,name=ssh_auth_sock,json=sshAuthSock,proto3" json:"ssh_auth_sock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{2}
}

func (x *RunCommandRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunCommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *RunCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunCommandRequest) GetUseShell() bool {
	if x != nil {
		return x.UseShell
	}
	return false
}

func (x *RunCommandRequest) GetSshAuthSock() string {
	if x != nil {
		return x.SshAuthSock
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Signal        ProcessSignal          `protobuf:"varint,2,opt,name=signal,proto3,enum=centaurx.runner.v1.ProcessSignal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{5}
}

func (x *SignalRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SignalRequest) GetSignal() ProcessSignal {
	if x != nil {
		return x.Signal
	}
	return ProcessSignal_PROCESS_SIGNAL_UNSPECIFIED
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{6}
}

func (x *SignalResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SignalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageRequest) Reset() {
	*x = UsageRequest{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageRequest) ProtoMessage() {}

func (x *UsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageRequest.ProtoReflect.Descriptor instead.
func (*UsageRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{7}
}

type UsageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Chatgpt         bool                   `protobuf:"varint,1,opt,name=chatgpt,proto3" json:"chatgpt,omitempty"`
	PrimaryWindow   *UsageWindow           `protobuf:"bytes,2,opt,name=primary_window,json=primaryWindow,proto3" json:"primary_window,omitempty"`
	SecondaryWindow *UsageWindow           `protobuf:"bytes,3,opt,name=secondary_window,json=secondaryWindow,proto3" json:"secondary_window,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UsageResponse) Reset() {
	*x = UsageResponse{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageResponse) ProtoMessage() {}

func (x *UsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageResponse.ProtoReflect.Descriptor instead.
func (*UsageResponse) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{8}
}

func (x *UsageResponse) GetChatgpt() bool {
	if x != nil {
		return x.Chatgpt
	}
	return false
}

func (x *UsageResponse) GetPrimaryWindow() *UsageWindow {
	if x != nil {
		return x.PrimaryWindow
	}
	return nil
}

func (x *UsageResponse) GetSecondaryWindow() *UsageWindow {
	if x != nil {
		return x.SecondaryWindow
	}
	return nil
}

type UsageWindow struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UsedPercent        float64                `protobuf:"fixed64,1,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	LimitWindowSeconds int64                  `protobuf:"varint,2,opt,name=limit_window_seconds,json=limitWindowSeconds,proto3" json:"limit_window_seconds,omitempty"`
	ResetAt            int64                  `protobuf:"varint,3,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UsageWindow) Reset() {
	*x = UsageWindow{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageWindow) ProtoMessage() {}

func (x *UsageWindow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageWindow.ProtoReflect.Descriptor instead.
func (*UsageWindow) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{9}
}

func (x *UsageWindow) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *UsageWindow) GetLimitWindowSeconds() int64 {
	if x != nil {
		return x.LimitWindowSeconds
	}
	return 0
}

func (x *UsageWindow) GetResetAt() int64 {
	if x != nil {
		return x.ResetAt
	}
	return 0
}

type RunnerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RunnerEvent_Exec
	//	*RunnerEvent_CommandOutput
	//	*RunnerEvent_Status
	Payload       isRunnerEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerEvent) Reset() {
	*x = RunnerEvent{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerEvent) ProtoMessage() {}

func (x *RunnerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerEvent.ProtoReflect.Descriptor instead.
func (*RunnerEvent) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{10}
}

func (x *RunnerEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunnerEvent) GetPayload() isRunnerEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunnerEvent) GetExec() *ExecEvent {
	if x != nil {
		if x, ok := x.Payload.(*RunnerEvent_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *RunnerEvent) GetCommandOutput() *CommandOutput {
	if x != nil {
		if x, ok := x.Payload.(*RunnerEvent_CommandOutput); ok {
			return x.CommandOutput
		}
	}
	return nil
}

func (x *RunnerEvent) GetStatus() *RunStatus {
	if x != nil {
		if x, ok := x.Payload.(*RunnerEvent_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isRunnerEvent_Payload interface {
	isRunnerEvent_Payload()
}

type RunnerEvent_Exec struct {
	Exec *ExecEvent `protobuf:"bytes,2,opt,name=exec,proto3,oneof"`
}

type RunnerEvent_CommandOutput struct {
	CommandOutput *CommandOutput `protobuf:"bytes,3,opt,name=command_output,json=commandOutput,proto3,oneof"`
}

type RunnerEvent_Status struct {
	Status *RunStatus `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

func (*RunnerEvent_Exec) isRunnerEvent_Payload() {}

func (*RunnerEvent_CommandOutput) isRunnerEvent_Payload() {}

func (*RunnerEvent_Status) isRunnerEvent_Payload() {}

type RunStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RunState               `protobuf:"varint,1,opt,name=state,proto3,enum=centaurx.runner.v1.RunState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStatus) Reset() {
	*x = RunStatus{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStatus) ProtoMessage() {}

func (x *RunStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStatus.ProtoReflect.Descriptor instead.
func (*RunStatus) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{11}
}

func (x *RunStatus) GetState() RunState {
	if x != nil {
		return x.State
	}
	return RunState_RUN_STATE_UNSPECIFIED
}

func (x *RunStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommandOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        StreamKind             `protobuf:"varint,1,opt,name=stream,proto3,enum=centaurx.runner.v1.StreamKind" json:"stream,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{12}
}

func (x *CommandOutput) GetStream() StreamKind {
	if x != nil {
		return x.Stream
	}
	return StreamKind_STREAM_KIND_UNSPECIFIED
}

func (x *CommandOutput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ExecEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=centaurx.runner.v1.EventType" json:"type,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Usage         *TurnUsage             `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Item          *ItemEvent             `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	Error         *ErrorEvent            `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Raw           []byte                 `protobuf:"bytes,7,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecEvent) Reset() {
	*x = ExecEvent{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEvent) ProtoMessage() {}

func (x *ExecEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecEvent.ProtoReflect.Descriptor instead.
func (*ExecEvent) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{13}
}

func (x *ExecEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ExecEvent) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ExecEvent) GetUsage() *TurnUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ExecEvent) GetItem() *ItemEvent {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ExecEvent) GetError() *ErrorEvent {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExecEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecEvent) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type TurnUsage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InputTokens       int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	CachedInputTokens int32                  `protobuf:"varint,2,opt,name=cached_input_tokens,json=cachedInputTokens,proto3" json:"cached_input_tokens,omitempty"`
	OutputTokens      int32                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TurnUsage) Reset() {
	*x = TurnUsage{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnUsage) ProtoMessage() {}

func (x *TurnUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnUsage.ProtoReflect.Descriptor instead.
func (*TurnUsage) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{14}
}

func (x *TurnUsage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TurnUsage) GetCachedInputTokens() int32 {
	if x != nil {
		return x.CachedInputTokens
	}
	return 0
}

func (x *TurnUsage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type ItemEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             ItemType               `protobuf:"varint,2,opt,name=type,proto3,enum=centaurx.runner.v1.ItemType" json:"type,omitempty"`
	Text             string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Command          string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	AggregatedOutput string                 `protobuf:"bytes,5,opt,name=aggregated_output,json=aggregatedOutput,proto3" json:"aggregated_output,omitempty"`
	ExitCode         *int32                 `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Changes          []*FileChange          `protobuf:"bytes,8,rep,name=changes,proto3" json:"changes,omitempty"`
	Query            string                 `protobuf:"bytes,9,opt,name=query,proto3" json:"query,omitempty"`
	Items            []*TodoItem            `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	Raw              []byte                 `protobuf:"bytes,11,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ItemEvent) Reset() {
	*x = ItemEvent{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemEvent) ProtoMessage() {}

func (x *ItemEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemEvent.ProtoReflect.Descriptor instead.
func (*ItemEvent) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{15}
}

func (x *ItemEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemEvent) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_ITEM_TYPE_UNSPECIFIED
}

func (x *ItemEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ItemEvent) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ItemEvent) GetAggregatedOutput() string {
	if x != nil {
		return x.AggregatedOutput
	}
	return ""
}

func (x *ItemEvent) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ItemEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ItemEvent) GetChanges() []*FileChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ItemEvent) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ItemEvent) GetItems() []*TodoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemEvent) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type FileChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{16}
}

func (x *FileChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChange) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type TodoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoItem) Reset() {
	*x = TodoItem{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoItem) ProtoMessage() {}

func (x *TodoItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoItem.ProtoReflect.Descriptor instead.
func (*TodoItem) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{17}
}

func (x *TodoItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TodoItem) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{18}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_runner_v1_runner_proto protoreflect.FileDescriptor

const file_proto_runner_v1_runner_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/runner/v1/runner.proto\x12\x12centaurx.runner.v1\"\xab\x01\n" +
	"\vExecRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04json\x18\x05 \x01(\bR\x04json\x12\"\n" +
	"\rssh_auth_sock\x18\x06 \x01(\tR\vsshAuthSock\"\xdd\x01\n" +
	"\x11ExecResumeRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12*\n" +
	"\x11resume_session_id\x18\x05 \x01(\tR\x0fresumeSessionId\x12\x12\n" +
	"\x04json\x18\x06 \x01(\bR\x04json\x12\"\n" +
	"\rssh_auth_sock\x18\a \x01(\tR\vsshAuthSock\"\xa6\x01\n" +
	"\x11RunCommandRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x1b\n" +
	"\tuse_shell\x18\x04 \x01(\bR\buseShell\x12\"\n" +
	"\rssh_auth_sock\x18\x05 \x01(\tR\vsshAuthSock\"\r\n" +
	"\vPingRequest\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"a\n" +
	"\rSignalRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x129\n" +
	"\x06signal\x18\x02 \x01(\x0e2!.centaurx.runner.v1.ProcessSignalR\x06signal\":\n" +
	"\x0eSignalResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0e\n" +
	"\fUsageRequest\"\xbd\x01\n" +
	"\rUsageResponse\x12\x18\n" +
	"\achatgpt\x18\x01 \x01(\bR\achatgpt\x12F\n" +
	"\x0eprimary_window\x18\x02 \x01(\v2\x1f.centaurx.runner.v1.UsageWindowR\rprimaryWindow\x12J\n" +
	"\x10secondary_window\x18\x03 \x01(\v2\x1f.centaurx.runner.v1.UsageWindowR\x0fsecondaryWindow\"}\n" +
	"\vUsageWindow\x12!\n" +
	"\fused_percent\x18\x01 \x01(\x01R\vusedPercent\x120\n" +
	"\x14limit_window_seconds\x18\x02 \x01(\x03R\x12limitWindowSeconds\x12\x19\n" +
	"\breset_at\x18\x03 \x01(\x03R\aresetAt\"\xe9\x01\n" +
	"\vRunnerEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x123\n" +
	"\x04exec\x18\x02 \x01(\v2\x1d.centaurx.runner.v1.ExecEventH\x00R\x04exec\x12J\n" +
	"\x0ecommand_output\x18\x03 \x01(\v2!.centaurx.runner.v1.CommandOutputH\x00R\rcommandOutput\x127\n" +
	"\x06status\x18\x04 \x01(\v2\x1d.centaurx.runner.v1.RunStatusH\x00R\x06statusB\t\n" +
	"\apayload\"v\n" +
	"\tRunStatus\x122\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1c.centaurx.runner.v1.RunStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"[\n" +
	"\rCommandOutput\x126\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1e.centaurx.runner.v1.StreamKindR\x06stream\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xa5\x02\n" +
	"\tExecEvent\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.centaurx.runner.v1.EventTypeR\x04type\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x123\n" +
	"\x05usage\x18\x03 \x01(\v2\x1d.centaurx.runner.v1.TurnUsageR\x05usage\x121\n" +
	"\x04item\x18\x04 \x01(\v2\x1d.centaurx.runner.v1.ItemEventR\x04item\x124\n" +
	"\x05error\x18\x05 \x01(\v2\x1e.centaurx.runner.v1.ErrorEventR\x05error\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x10\n" +
	"\x03raw\x18\a \x01(\fR\x03raw\"\x83\x01\n" +
	"\tTurnUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12.\n" +
	"\x13cached_input_tokens\x18\x02 \x01(\x05R\x11cachedInputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x05R\foutputTokens\"\x86\x03\n" +
	"\tItemEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.centaurx.runner.v1.ItemTypeR\x04type\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12+\n" +
	"\x11aggregated_output\x18\x05 \x01(\tR\x10aggregatedOutput\x12 \n" +
	"\texit_code\x18\x06 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x128\n" +
	"\achanges\x18\b \x03(\v2\x1e.centaurx.runner.v1.FileChangeR\achanges\x12\x14\n" +
	"\x05query\x18\t \x01(\tR\x05query\x122\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x1c.centaurx.runner.v1.TodoItemR\x05items\x12\x10\n" +
	"\x03raw\x18\v \x01(\fR\x03rawB\f\n" +
	"\n" +
	"_exit_code\"4\n" +
	"\n" +
	"FileChange\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"<\n" +
	"\bTodoItem\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted\"&\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*y\n" +
	"\rProcessSignal\x12\x1e\n" +
	"\x1aPROCESS_SIGNAL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROCESS_SIGNAL_HUP\x10\x01\x12\x17\n" +
	"\x13PROCESS_SIGNAL_TERM\x10\x02\x12\x17\n" +
	"\x13PROCESS_SIGNAL_KILL\x10\x03*j\n" +
	"\bRunState\x12\x19\n" +
	"\x15RUN_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RUN_STATE_STARTED\x10\x01\x12\x16\n" +
	"\x12RUN_STATE_FINISHED\x10\x02\x12\x14\n" +
	"\x10RUN_STATE_FAILED\x10\x03*Y\n" +
	"\n" +
	"StreamKind\x12\x1b\n" +
	"\x17STREAM_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STREAM_KIND_STDOUT\x10\x01\x12\x16\n" +
	"\x12STREAM_KIND_STDERR\x10\x02*\xe5\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EVENT_THREAD_STARTED\x10\x01\x12\x16\n" +
	"\x12EVENT_TURN_STARTED\x10\x02\x12\x18\n" +
	"\x14EVENT_TURN_COMPLETED\x10\x03\x12\x15\n" +
	"\x11EVENT_TURN_FAILED\x10\x04\x12\x16\n" +
	"\x12EVENT_ITEM_STARTED\x10\x05\x12\x16\n" +
	"\x12EVENT_ITEM_UPDATED\x10\x06\x12\x18\n" +
	"\x14EVENT_ITEM_COMPLETED\x10\a\x12\x0f\n" +
	"\vEVENT_ERROR\x10\b*\xd4\x01\n" +
	"\bItemType\x12\x19\n" +
	"\x15ITEM_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ITEM_AGENT_MESSAGE\x10\x01\x12\x12\n" +
	"\x0eITEM_REASONING\x10\x02\x12\x1a\n" +
	"\x16ITEM_COMMAND_EXECUTION\x10\x03\x12\x14\n" +
	"\x10ITEM_FILE_CHANGE\x10\x04\x12\x16\n" +
	"\x12ITEM_MCP_TOOL_CALL\x10\x05\x12\x13\n" +
	"\x0fITEM_WEB_SEARCH\x10\x06\x12\x12\n" +
	"\x0eITEM_TODO_LIST\x10\a\x12\x0e\n" +
	"\n" +
	"ITEM_ERROR\x10\b2\xf8\x03\n" +
	"\x06Runner\x12J\n" +
	"\x04Exec\x12\x1f.centaurx.runner.v1.ExecRequest\x1a\x1f.centaurx.runner.v1.RunnerEvent0\x01\x12V\n" +
	"\n" +
	"ExecResume\x12%.centaurx.runner.v1.ExecResumeRequest\x1a\x1f.centaurx.runner.v1.RunnerEvent0\x01\x12V\n" +
	"\n" +
	"RunCommand\x12%.centaurx.runner.v1.RunCommandRequest\x1a\x1f.centaurx.runner.v1.RunnerEvent0\x01\x12I\n" +
	"\x04Ping\x12\x1f.centaurx.runner.v1.PingRequest\x1a .centaurx.runner.v1.PingResponse\x12V\n" +
	"\rSignalSession\x12!.centaurx.runner.v1.SignalRequest\x1a\".centaurx.runner.v1.SignalResponse\x12O\n" +
	"\bGetUsage\x12 .centaurx.runner.v1.UsageRequest\x1a!.centaurx.runner.v1.UsageResponseB1Z/pkt.systems/centaurx/internal/runnerpb;runnerpbb\x06proto3"

var (
	file_proto_runner_v1_runner_proto_rawDescOnce sync.Once
	file_proto_runner_v1_runner_proto_rawDescData []byte
)

func file_proto_runner_v1_runner_proto_rawDescGZIP() []byte {
	file_proto_runner_v1_runner_proto_rawDescOnce.Do(func() {
		file_proto_runner_v1_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_runner_v1_runner_proto_rawDesc), len(file_proto_runner_v1_runner_proto_rawDesc)))
	})
	return file_proto_runner_v1_runner_proto_rawDescData
}

var file_proto_runner_v1_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_runner_v1_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_runner_v1_runner_proto_goTypes = []any{
	(ProcessSignal)(0),        // 0: centaurx.runner.v1.ProcessSignal
	(RunState)(0),             // 1: centaurx.runner.v1.RunState
	(StreamKind)(0),           // 2: centaurx.runner.v1.StreamKind
	(EventType)(0),            // 3: centaurx.runner.v1.EventType
	(ItemType)(0),             // 4: centaurx.runner.v1.ItemType
	(*ExecRequest)(nil),       // 5: centaurx.runner.v1.ExecRequest
	(*ExecResumeRequest)(nil), // 6: centaurx.runner.v1.ExecResumeRequest
	(*RunCommandRequest)(nil), // 7: centaurx.runner.v1.RunCommandRequest
	(*PingRequest)(nil),       // 8: centaurx.runner.v1.PingRequest
	(*PingResponse)(nil),      // 9: centaurx.runner.v1.PingResponse
	(*SignalRequest)(nil),     // 10: centaurx.runner.v1.SignalRequest
	(*SignalResponse)(nil),    // 11: centaurx.runner.v1.SignalResponse
	(*UsageRequest)(nil),      // 12: centaurx.runner.v1.UsageRequest
	(*UsageResponse)(nil),     // 13: centaurx.runner.v1.UsageResponse
	(*UsageWindow)(nil),       // 14: centaurx.runner.v1.UsageWindow
	(*RunnerEvent)(nil),       // 15: centaurx.runner.v1.RunnerEvent
	(*RunStatus)(nil),         // 16: centaurx.runner.v1.RunStatus
	(*CommandOutput)(nil),     // 17: centaurx.runner.v1.CommandOutput
	(*ExecEvent)(nil),         // 18: centaurx.runner.v1.ExecEvent
	(*TurnUsage)(nil),         // 19: centaurx.runner.v1.TurnUsage
	(*ItemEvent)(nil),         // 20: centaurx.runner.v1.ItemEvent
	(*FileChange)(nil),        // 21: centaurx.runner.v1.FileChange
	(*TodoItem)(nil),          // 22: centaurx.runner.v1.TodoItem
	(*ErrorEvent)(nil),        // 23: centaurx.runner.v1.ErrorEvent
}
var file_proto_runner_v1_runner_proto_depIdxs = []int32{
	0,  // 0: centaurx.runner.v1.SignalRequest.signal:type_name -> centaurx.runner.v1.ProcessSignal
	14, // 1: centaurx.runner.v1.UsageResponse.primary_window:type_name -> centaurx.runner.v1.UsageWindow
	14, // 2: centaurx.runner.v1.UsageResponse.secondary_window:type_name -> centaurx.runner.v1.UsageWindow
	18, // 3: centaurx.runner.v1.RunnerEvent.exec:type_name -> centaurx.runner.v1.ExecEvent
	17, // 4: centaurx.runner.v1.RunnerEvent.command_output:type_name -> centaurx.runner.v1.CommandOutput
	16, // 5: centaurx.runner.v1.RunnerEvent.status:type_name -> centaurx.runner.v1.RunStatus
	1,  // 6: centaurx.runner.v1.RunStatus.state:type_name -> centaurx.runner.v1.RunState
	2,  // 7: centaurx.runner.v1.CommandOutput.stream:type_name -> centaurx.runner.v1.StreamKind
	3,  // 8: centaurx.runner.v1.ExecEvent.type:type_name -> centaurx.runner.v1.EventType
	19, // 9: centaurx.runner.v1.ExecEvent.usage:type_name -> centaurx.runner.v1.TurnUsage
	20, // 10: centaurx.runner.v1.ExecEvent.item:type_name -> centaurx.runner.v1.ItemEvent
	23, // 11: centaurx.runner.v1.ExecEvent.error:type_name -> centaurx.runner.v1.ErrorEvent
	4,  // 12: centaurx.runner.v1.ItemEvent.type:type_name -> centaurx.runner.v1.ItemType
	21, // 13: centaurx.runner.v1.ItemEvent.changes:type_name -> centaurx.runner.v1.FileChange
	22, // 14: centaurx.runner.v1.ItemEvent.items:type_name -> centaurx.runner.v1.TodoItem
	5,  // 15: centaurx.runner.v1.Runner.Exec:input_type -> centaurx.runner.v1.ExecRequest
	6,  // 16: centaurx.runner.v1.Runner.ExecResume:input_type -> centaurx.runner.v1.ExecResumeRequest
	7,  // 17: centaurx.runner.v1.Runner.RunCommand:input_type -> centaurx.runner.v1.RunCommandRequest
	8,  // 18: centaurx.runner.v1.Runner.Ping:input_type -> centaurx.runner.v1.PingRequest
	10, // 19: centaurx.runner.v1.Runner.SignalSession:input_type -> centaurx.runner.v1.SignalRequest
	12, // 20: centaurx.runner.v1.Runner.GetUsage:input_type -> centaurx.runner.v1.UsageRequest
	15, // 21: centaurx.runner.v1.Runner.Exec:output_type -> centaurx.runner.v1.RunnerEvent
	15, // 22: centaurx.runner.v1.Runner.ExecResume:output_type -> centaurx.runner.v1.RunnerEvent
	15, // 23: centaurx.runner.v1.Runner.RunCommand:output_type -> centaurx.runner.v1.RunnerEvent
	9,  // 24: centaurx.runner.v1.Runner.Ping:output_type -> centaurx.runner.v1.PingResponse
	11, // 25: centaurx.runner.v1.Runner.SignalSession:output_type -> centaurx.runner.v1.SignalResponse
	13, // 26: centaurx.runner.v1.Runner.GetUsage:output_type -> centaurx.runner.v1.UsageResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_runner_v1_runner_proto_init() }
func file_proto_runner_v1_runner_proto_init() {
	if File_proto_runner_v1_runner_proto != nil {
		return
	}
	file_proto_runner_v1_runner_proto_msgTypes[10].OneofWrappers = []any{
		(*RunnerEvent_Exec)(nil),
		(*RunnerEvent_CommandOutput)(nil),
		(*RunnerEvent_Status)(nil),
	}
	file_proto_runner_v1_runner_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_runner_v1_runner_proto_rawDesc), len(file_proto_runner_v1_runner_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_runner_v1_runner_proto_goTypes,
		DependencyIndexes: file_proto_runner_v1_runner_proto_depIdxs,
		EnumInfos:         file_proto_runner_v1_runner_proto_enumTypes,
		MessageInfos:      file_proto_runner_v1_runner_proto_msgTypes,
	}.Build()
	File_proto_runner_v1_runner_proto = out.File
	file_proto_runner_v1_runner_proto_goTypes = nil
	file_proto_runner_v1_runner_proto_depIdxs = nil
}
